version: "3"

services:
  db:
    image: postgres:11
    container_name: 'ctr-db'
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: 'ctr'
    ports:
      - "8090:5432"
    volumes:
      - ~/.docker-conf/ctr-postgresql:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: 'ctr-pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: "guest@guest.com"
      PGADMIN_DEFAULT_PASSWORD: "12345678"
    ports:
      - "5001:80"
    depends_on:
      - db

  calcorte-api:
    container_name: 'ctr-api'
    build:
      context: ctr-backend
      dockerfile: Dockerfile
    image: edernilson/ctr-api:0.0.1
    ports:
      - 8080:8080
    depends_on:
      - 'db'
    environment:
        - 'GOOGLE_API_KEY=API_KEY'
        - 'SPRING_PROFILES_ACTIVE=prod'
        - 'POSTGRES_URL=jdbc:postgresql://db:5432/ctr'
        - 'POSTGRES_USER=postgres'
        - 'POSTGRES_PASSWORD=12345678'
        - 'CORS_ORIGINS=http://localhost:8081,http://192.168.1.72:8081'

